mongo:
    build: ./mongo
    expose:
        - "27017"
        - "28017"
    ports:
        - "27017:27017"
        - "28017:28017"
    volumes:
        - ~/data/mongo:/data/db
        - ~/log/mongo:/var/log/mongodb

apache:
    build: ./apache
    expose:
        - "80"
        - "9003"
    ports:
        - "80:80"
    volumes:
        - ~/log/apache:/var/log/apache2
        - ~/site:/site
    links:
        - "mongo"
        - "elasticsearch"

elasticsearch:
    build: ./elasticsearch

    expose:
        - "9200"
    ports:
        - "9200:9200"
    volumes:
        - ~/log/elastic:/var/log/elasticsearch
        - ~/data/elastic:/usr/share/elasticsearch/data
